### ISSUE TITLE
Add tests blocks for fire rate

### ISSUE THREAD

**Issue by EvoLandEco** [tresinformal/game#519]

**Comment by TheoPannetier** [comment]
No need to make a separate issue for writing tests. Since we use [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development), writing a test should always be part (and in fact, the first step) towards solving an issue 😉 

I don't know if someone else introduced you to the framework already, so assuming not here is how it works:
1. Open an issue to address a small, fairly delimited problem, e.g. as you did for #516
2. Write a test that will make sure that the problem must be solved in order for the test to pass. The test should ideally be easy to read, close to human language. It helps to first identify a rule or statement (in english, not code) that you want to become true once the issue is solved. Then write it out in code as a test to make sure this statement is enforced.
For example, in the case of #516, I guess the statement would be 

> **"If two projectiles are of a different type, they should have a different firing rate"**

and the corresponding test would be (in pseudocode, I have no idea what projectiles are made of in the game):

```
projectile a_projectile;
projectile another_projectile;

a_projectile.set_type("A");
another_projectile.set_type("B");

assert(a_projectile.get_firing_rate() != another_projectile.get_firing_rate())
```

3. Once the test is written, it should not pass (else that would mean your problem was aleady solved!). Now, you (or someone else) can change the code of the game to make sure the test passes 😁 
4. Done. Once the test passes, the problem is (by definition) solved and we are (by definition) happy!

**Comment by richelbilderbeek** [comment]
Excellent @TheoPannetier, this blends in nicely with my review of #518, thanks!

**Comment by EvoLandEco** [comment]
Great explanation about the idea of the test-driven development. I should have written the tests before implementing new features. I learned quite a lot from this. I'm going to add some tests myself now to see whether I can address all the aspects of the problem.
